(**** beginning of start.txt ****)
(**** begin initilization commands ****)
G21 (set units to mm)
G90 (set positioning to absolute)
M108 S255 (set extruder speed to maximum)
M103 (Make sure extruder is off)
M104 S225 T0 (set extruder temperature)
(**** end initilization commands ****)
(**** begin pre-wipe commands ****)
G1 X0 Y0.0 Z10 F2000.0 (move to waiting position)
M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)
M101 (Extruder on, forward)
G04 P5000 (Wait t/1000 seconds)
M103 (Extruder off)
(**** end pre-wipe commands ****)
M01 (Remove the test extrusion then click ok.)
(**** end of start.txt ****)

